### ISSUE TITLE
Scaling down microceph does not update relation data

### ISSUE THREAD

**Issue by gboutry** [canonical/charm-microceph#121]
Hey, I had a 3 unit microceph deployed with charm rev 85, and snap rev 1246.

I performed a scale down by removing the leader unit. This step took a lot of time to complete, and after the unit left, the relation data was not updated:

Show unit shows:
```
  - relation-id: 147
    endpoint: ceph
    cross-model: true
    related-endpoint: ceph
    application-data:
      ceph-mon-public-addresses: '["10.149.73.169", "10.149.73.186", "10.149.73.187"]'
    related-units:
      microceph/1:
        in-scope: true
        data:
          egress-subnets: 10.149.73.186/32
          ingress-address: 10.149.73.186
          private-address: 10.149.73.186
      microceph/2:
        in-scope: true
        data:
          egress-subnets: 10.149.73.187/32
          ingress-address: 10.149.73.187
          private-address: 10.149.73.187
```

`ceph-mon-public-addresses` still has the removed unit

To workaround this issue, I had to remove the glance-microceph and cincer-ceph-microceph relations, and re-relate.
