### ISSUE TITLE
Colocating charm Ceph-csi and Microceph breaks ceph commands

### ISSUE THREAD

**Issue by odufourc** [canonical/charm-microceph#157]
## Environment : 
* Ubuntu 24.04
* Microceph Squid/stable and latest/edge
* Canonical k8s 1.32/stable
* Charmed Ceph-csi 1.32/edge

The main idea is to be able to have a deployment where MicroCeph and Canonical k8s can be colocated on the same machine

## Reproducers : 
* Deploy base bundle with colocation of k8s, Microceph and Ceph-csi : 
```
applications:
  ceph-csi:
    bindings:
      ? ''
      : oam-space
      ceph-client: oam-space
    channel: 1.32/edge
    charm: ceph-csi
  k8s:
    bindings:
      ? ''
      : oam-space
    channel: 1.32/stable
    charm: k8s
    num_units: 3
    options:
      load-balancer-cidrs: 10.64.40.50-10.64.40.52
      load-balancer-enabled: true
      load-balancer-l2-interfaces: enp1s0
      load-balancer-l2-mode: true
    base: ubuntu@24.04
    to:
    - '6'
    - '7'
    - '8'
  microceph:
    bindings:
      ? ''
      : oam-space
    channel: squid/stable
    charm: microceph
    num_units: 3
    series: noble
    to:
    - '6'
    - '7'
    - '8'
machines:
  '6':
    constraints: tags=foundation-nodes,k8s zones=zone1
    base: ubuntu@24.04
  '7':
    constraints: tags=foundation-nodes,k8s zones=zone2
    base: ubuntu@24.04
  '8':
    constraints: tags=foundation-nodes,k8s zones=zone3
    base: ubuntu@24.04
base: ubuntu@24.04
relations:
- ['ceph-csi:kubernetes', 'k8s:juju-info']
```
* Add OSD to each MicroCeph unit
* Relate MicroCeph and Ceph-CSI

## Expected behaviour : 
* Ceph-csi gets in active idle state and the pools related to k8s are created successfully

## Current result : 
* Ceph-csi is stuck in waiting state and the relation between ceph-csi and microceph shows that Microceph doesn't provide any data on how to connect the Ceph cluster
### Logs from Ceph-Csi unit
> 2025-04-25 02:26:50 INFO unit.ceph-csi/1.juju-log server.go:406 ceph-client:15: HTTP Request: GET https://127.0.0.1:6443/api/v1/namespaces/default "HTTP/1.1 200 OK"
> 2025-04-25 02:26:50 WARNING unit.ceph-csi/1.juju-log server.go:406 ceph-client:15: Ceph relation is missing data: ['auth', 'key', 'mon_hosts']
> 2025-04-25 02:26:50 ERROR unit.ceph-csi/1.juju-log server.go:406 ceph-client:15: Caught ReconcilerError
> Traceback (most recent call last):
>   File "/var/lib/juju/agents/unit-ceph-csi-1/charm/venv/charms/reconciler.py", line 45, in reconcile
>     self.reconcile_function(event)
>   File "/var/lib/juju/agents/unit-ceph-csi-1/charm/./src/charm.py", line 406, in reconcile
>     self.check_ceph_client()
>   File "/var/lib/juju/agents/unit-ceph-csi-1/charm/./src/charm.py", line 392, in check_ceph_client
>     raise status.ReconcilerError("Ceph relation is missing data.")
> charms.contextual_status.ReconcilerError: Ceph relation is missing data.
> 2025-04-25 02:26:50 INFO unit.ceph-csi/1.juju-log server.go:406 ceph-client:15: Status context closed with: [WaitingStatus('Ceph relation is missing data.')]
> 2025-04-25 02:26:50 INFO juju.worker.uniter.operation runhook.go:186 ran "ceph-client-relation-changed" hook (via hook dispatching script: dispatch)

### Relation content
Application data is empty : 
> ceph-csi/0:
>   machine: "1"
>   opened-ports: []
>   public-address: 10.64.43.49
>   charm: ch:amd64/ceph-csi-75
>   leader: true
>   life: alive
>   relation-info:
>   - relation-id: 15
>     endpoint: ceph-client
>     related-endpoint: ceph
>     application-data: {}
>     related-units:
>       microceph/0:
>         in-scope: true
>         data:
>           egress-subnets: 10.64.43.48/32
>           ingress-address: 10.64.43.48
>           private-address: 10.64.43.48

### Logs from Microceph unit
> 2025-04-25 02:26:48 INFO unit.microceph/0.juju-log server.go:406 ceph:15: Storage not available, deferring event.
> 2025-04-25 02:26:49 INFO juju.worker.uniter.operation runhook.go:186 ran "ceph-relation-changed" hook (via hook dispatching script: dispatch)
> 2025-04-25 02:26:51 INFO unit.microceph/0.juju-log server.go:406 ceph:15: _on_relation_changed event
> 2025-04-25 02:26:51 WARNING unit.microceph/0.ceph-relation-changed logger.go:60 Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)')
> 2025-04-25 02:26:51 WARNING unit.microceph/0.juju-log server.go:406 ceph:15: Failed getting the number of OSDs: Command '['ceph', 'osd', 'ls']' returned non-zero exit status 1.
> 2025-04-25 02:26:51 INFO unit.microceph/0.juju-log server.go:406 ceph:15: Storage not available, deferring event.
> 2025-04-25 02:26:51 INFO unit.microceph/0.juju-log server.go:406 ceph:15: _on_relation_changed event

## Root cause
Ceph-csi installs the package Ceph-common which provides itself the ceph command, resulting in having multiple `ceph` commands but $PATH will give the priority to `/usr/bin/ceph` instead of `/snap/bin/ceph`.
Consequently all ceph commands executed by the charm will simply fail.

A solution would probably to ensure the charm is using the full path of the command `/snap/bin/ceph`

```
root@k8s-1:~# snap aliases microceph
Command                  Alias          Notes
microceph.ceph           ceph           manual,override
microceph.rados          rados          -
microceph.radosgw-admin  radosgw-admin  -
microceph.rbd            rbd            -

root@k8s-1:~# which ceph
/usr/bin/ceph
root@k8s-1:~# whereis ceph
ceph: /usr/bin/ceph /usr/lib/x86_64-linux-gnu/ceph /etc/ceph /usr/share/ceph /snap/bin/ceph /usr/share/man/man8/ceph.8.gz

root@k8s-1:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```
